### ISSUE TITLE
[iOS]: Cannot read property 'StepCount' of undefined

### ISSUE THREAD

**Issue by KushalDesai1** [doville/rn-fitness-tracker#52]
While trying to fetch today steps using the FitnessTrackerAPI, I am getting a promise rejection.

TypeError: Cannot read property 'StepCount' of undefined

Wanted to know if there is any change in the CoreMotion library from iOS. 

As per the apple official doc, there is a change I guess. Check [https://developer.apple.com/documentation/coremotion/cmpedometerdata/1613965-numberofsteps?language=objc](https://developer.apple.com/documentation/coremotion/cmpedometerdata/1613965-numberofsteps?language=objc)

**Comment by lukebars** [comment]
Hey, can you share a code snippet of what you're trying to do? We're using this library in production for multiple of our apps and we didn't have any issues.

**Comment by KushalDesai1** [comment]
I am trying to fetch step count from today using FitnessTrackerAPI.

`let todaySteps = await FitnessTrackerAPI.getStepsToday();
console.log("Today steps: "+todaySteps)
`

But I am getting error message:  'Cannot read property 'StepCount' of undefined'. And Promise gets rejected.

**Comment by lukebars** [comment]
@KushalDesai1 what version are you using?

**Comment by KushalDesai1** [comment]
> @KushalDesai1 what version are you using? `1.4.10` should fix this

I am using 1.4.8

**Comment by lukebars** [comment]
That should be it, there was a major bug in that version. Try upgrading to 1.4.10. It's a patch release, as per semantic versioning, so no breaking changes 😇

**Comment by lukebars** [comment]
@KushalDesai1 ping me if everything is okay

**Comment by KushalDesai1** [comment]
I am still getting same error message. Is it because of using a simulator?

**Comment by lukebars** [comment]
@KushalDesai1 I can't reproduce this issue. A small reproduction would be helpful though.

**Comment by rajaiogames** [comment]
I am using this plugins then getting the issue when Health application not launch and want to get the step count then not able to get step count, but when I open the Health app then it's reading perfactaly, 

So can you help me how can read the step count data without open Health app

**Comment by KushalDesai1** [comment]
I forgot to provide required permissions in the plist file.
