### ISSUE TITLE
Error: Unable to resolve module react-native-device-info

### ISSUE THREAD

**Issue by mykhailo-melnyk** [doville/rn-fitness-tracker#53]
I followed instruction from README but looks like dependencies not installed. Should I install dependent rn-fitness-tracker packages mannualy?
when I try to run my application I see:
![Screenshot at Jun 25 02-20-37](https://user-images.githubusercontent.com/14886932/123344171-f3906980-d55b-11eb-81d2-3295a3c4b702.png)

**Comment by lukebars** [comment]
Yes. You do need to run `yarn add react-native-device-info react-native-permissions` / `npm i react-native-device-info react-native-permissions`

**Comment by mykhailo-melnyk** [comment]
@lukebars thank you a lot!
can you please add it to documentation?

**Comment by lukebars** [comment]
@mykhailo-melnyk Sure! Done and dusted :shipit:

**Comment by mykhailo-melnyk** [comment]
thank you!
@lukebars do we have some chat where somebody can ask questions?
